<?php

namespace Nutricion\EmpresasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoTelefonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTelefonoRepository extends EntityRepository
{
}
