nutricion_empresas:
    path:     /empresas
    defaults: { _controller: NutricionEmpresasBundle:Default:empresas }

nutricion_crear_empresa:
    path:     /crear-empresa
    defaults: { _controller: NutricionEmpresasBundle:Default:crearEmpresa }

nutricion_perfil_empresa:
    path:     /perfil-empresa/{id}
    defaults: { _controller: NutricionEmpresasBundle:Default:empresa }

nutricion_perfiles:
    path:     /perfiles
    defaults: { _controller: NutricionEmpresasBundle:Default:perfiles }

nutricion_crear_perfil:
    path:     /crear-perfil
    defaults: { _controller: NutricionEmpresasBundle:Default:crearPerfil }
