parameters:
#    nutricion_empresas.example.class: Nutricion\EmpresasBundle\Example

services:
#    nutricion_empresas.example:
#        class: %nutricion_empresas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
