Nutricion\EmpresasBundle\Entity\Empresas:
  properties:
   empresa:
    - NotBlank: { message: 'Empresa no puede quedar vacío' }
   email:
    - NotBlank: { message: 'El Email es obligatorio' }
   telefono:
    - NotBlank: { message: 'El Teléfono es importante' }
   direccion:
    - NotBlank: { message: 'La Dirección no puede quedar vacía' }
   observaciones:
    - NotBlank: { message: 'Las Observaciones son obligatorias' }

# Nutricion\EmpresasBundle\Entity\Perfiles:
#   properties:
#    nombres:
#     - NotBlank: { message: 'El nombre no puede quedar vacío' }
#    apellidos:
#     - NotBlank: { message: 'El Email es obligatorio' }
